services:

  agenda_api: 
     container_name: springboot-agendaapi
     build:
         context: . 
         dockerfile: Dockerfile
     ports:
        - "8081:8081"
     networks:
        - agendaapi-network
     depends_on:
        - postgres

  postgres:
    image: postgres:15
    container_name: agenda_postgres
    restart: always
    environment:
      POSTGRES_DB: bd_apiagenda
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: coti
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - agendaapi-network

volumes:
  postgres_data:

networks:
  agendaapi-network: